name: inspector
description: A demo project that shows status of gamepads attached to Windows.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^3.9.0
  win32_gamepad: 
    path: ../..

dev_dependencies:
  flutter_lints: ^1.0.0